### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [oddisland/Switch#1]
Good day @oddisland  I am a graphic designer and I notice that the project doesn't have a logo yet. I would like to propose a logo contribution if you will allow me. It is my gift to the project for free. I just need your permission first before I begin my design. Hoping for a positive feedback. Thanks and best regards! 

-Tobaloidee

**Comment by jacoblee53** [comment]
Hi, @Tobaloidee.
I'm so happy that you would like to propose a logo for this project!
If you want, just do it.
Thanks and best regards!

- oddisland

**Comment by Tobaloidee** [comment]
Thanks for the positive response @oddisland I will start my design and show it here when finished.. :)

**Comment by Tobaloidee** [comment]
Hi @oddisland here's what i came up to and i think fits your project! still open for suggestions. I also made color options for your preference.

![switch-01](https://user-images.githubusercontent.com/36028424/42322293-76e23726-808e-11e8-88e6-e99a8a8e6e6f.png)
![switch-02](https://user-images.githubusercontent.com/36028424/42322305-80d8cf7e-808e-11e8-8ac4-73c6ba344856.png)
